# import と関数定義

In [6]:
import sys
sys.path.append("/Users/ishimiwataru/Downloads/DNN_code_colab_lesson_1_2")

In [12]:
import numpy as np
from common import functions

def print_vec(text,vec):
    print("***"+ text +"***")
    print(vec)
    print("shape:" + str(vec.shape))
    print("")

# 順伝播(単層・単ユニット)

In [14]:
# 順伝播（単層・単ユニット）

# 重み
#W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = np.array(0.5)

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


***重み***
[3 4]
shape:(2,)

***バイアス***
0.5
shape:()

***入力***
[2 3]
shape:(2,)

***総入力***
18.5
shape:()

***中間層出力***
18.5
shape:()



# 順伝播（単層・複数ユニット）
試してみよう配列の初期化（W=rand(4,3)）

In [21]:
# 順伝播（単層・複数ユニット）

# 重み
""""W = np.array([
    [0.1, 0.2, 0.3,0], 
    [0.2, 0.3, 0.4, 0.5], 
    [0.3, 0.4, 0.5, 1],
])"""

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)

#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


***重み***
[[0.42096529 0.77721124 0.64213436]
 [0.51858096 0.05498159 0.34246053]
 [0.35474308 0.17477473 0.67173965]
 [0.57556978 0.15734161 0.7875791 ]]
shape:(4, 3)

***バイアス***
[0.1 0.2 0.3]
shape:(3,)

***入力***
[ 1.  5.  2. -1.]
shape:(4,)

***総入力***
[3.24778646 1.44432702 3.21033724]
shape:(3,)

***中間層出力***
[0.96259349 0.80912382 0.96122144]
shape:(3,)



# 順伝播（３層・複数ユニット）

In [22]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネットワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    input_layer_size = 3
    hidden_layer_size_1=10
    hidden_layer_size_2=5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1,hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size_1)
    network['b2'] =  np.random.rand(hidden_layer_size_2)
    network['b3'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("中間層出力2", z2)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

***入力***
[1. 2. 4.]
shape:(3,)

##### ネットワークの初期化 #####
***重み1***
[[0.3759906  0.58077013 0.53472809 0.24571699 0.22036025 0.81277497
  0.00725114 0.05259152 0.05636985 0.22435196]
 [0.67911949 0.9396775  0.89259783 0.43241578 0.61766116 0.39743991
  0.55518532 0.30567236 0.33086937 0.4428257 ]
 [0.25023066 0.52032832 0.32066102 0.56406242 0.92371113 0.10529627
  0.87422404 0.13842869 0.70471439 0.86894657]]
shape:(3, 10)

***重み2***
[[0.78922704 0.48664503 0.93696689 0.36342475 0.5717702 ]
 [0.40642927 0.65168968 0.22977789 0.0238755  0.11524662]
 [0.3258952  0.37022753 0.49943318 0.99711922 0.22671917]
 [0.32012035 0.07735356 0.63747624 0.0193294  0.02678093]
 [0.96788478 0.93865815 0.56280258 0.32554066 0.16813028]
 [0.02106969 0.1996359  0.47771005 0.4759528  0.16326634]
 [0.04835873 0.83540932 0.28198934 0.25573656 0.9088975 ]
 [0.59380746 0.4781003  0.075814   0.42428837 0.54470287]
 [0.37704174 0.70132508 0.11681882 0.90987537 0.65784022]
 [0.90363595 0.02606467 0.72064277 0.09737

# 他クラス分類（２−３−４）
試してみようノード構成を３−５−６~に変更してみよう

In [23]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    
    input_layer_size = 3
    hidden_layer_size=5
    output_layer_size = 6
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
***重み1***
[[0.06457131 0.56950247 0.8056994  0.8730734  0.757928  ]
 [0.80890905 0.51226348 0.81395097 0.36217449 0.32916206]
 [0.61129561 0.9846758  0.4049057  0.61860123 0.30090411]]
shape:(3, 5)

***重み2***
[[0.86485766 0.45554286 0.92166324 0.58215748 0.65386627 0.76763309]
 [0.23054949 0.36618228 0.71375433 0.67564166 0.74514509 0.83931537]
 [0.90488123 0.09671234 0.49766844 0.66488797 0.56948929 0.57656173]
 [0.48952957 0.10779885 0.25914776 0.76438833 0.41152703 0.131976  ]
 [0.80581221 0.97091344 0.2251171  0.71718929 0.20364958 0.31919142]]
shape:(5, 6)

***バイアス1***
[0.17556621 0.58778953 0.82462856 0.48522863 0.83782108]
shape:(5,)

***バイアス2***
[0.26922603 0.84103678 0.17934916 0.39221999 0.85227776 0.46738956]
shape:(6,)

##### 順伝播開始 #####
***総入力1***
[3.69184243 5.13584635 4.472947   3.9384547  3.15678552]
shape:(5,)

***中間層出力1***
[3.69184243 5.13584635 4.472947   3.9384547  3.15678552]
shape:(5,)

***総入力2***
[13.16546313  8.32560069 11.20504987 14.2599

# 回帰（２−３−２ネットワーク）
試してみよう_ノード構成を３−５~４に変更してみよう

In [24]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size=5
    output_layer_size = 4
    
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 3., 1])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
***重み1***
[[0.05524168 0.44379616 0.53628055 0.3508082  0.89431296]
 [0.0510514  0.89976094 0.36141635 0.4781822  0.50206014]
 [0.64369279 0.36412984 0.13896958 0.13605729 0.38874401]]
shape:(3, 5)

***重み2***
[[0.11688386 0.3185074  0.99015467 0.45835345]
 [0.09957639 0.49024693 0.95183375 0.04689891]
 [0.1957069  0.91739157 0.99173167 0.51014509]
 [0.0992865  0.17199101 0.33870725 0.1868599 ]
 [0.5772766  0.05798224 0.85188437 0.23577529]]
shape:(5, 4)

***バイアス1***
[0.09374731 0.51679306 0.09720161 0.43751692 0.64207   ]
shape:(5,)

***バイアス2***
[0.35018942 0.34645376 0.38451072 0.27357387]
shape:(4,)

##### 順伝播開始 #####
***総入力1***
[2.18217014 3.85250062 1.77322359 2.1528614  3.70673526]
shape:(5,)

***中間層出力1***
[2.18217014 3.85250062 1.77322359 2.1528614  3.70673526]
shape:(5,)

***総入力2***
[ 3.6894617   5.14210569 11.85759841  3.63529851]
shape:(4,)

***出力1***
[ 3.6894617   5.14210569 11.85759841  3.63529851]
shape:(4,)

出力合計: 24.324464310114724

##### 結果表示 #####

# ２値分類（２−３−１ネットワーク）
試してみよう_ノード構成を５−１０−２０ー１に変更してみよう

In [25]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネットワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)
    
    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
***総入力1***
[1.71104546 4.92065362 7.75013795 1.75830799 4.55204153 7.02231455
 1.99393682 4.98794094 7.72271424 1.50531795]
shape:(10,)

***中間層出力1***
[1.71104546 4.92065362 7.75013795 1.75830799 4.55204153 7.02231455
 1.99393682 4.98794094 7.72271424 1.50531795]
shape:(10,)

***総入力2***
[20.59820718 19.51956017 19.20227783 26.70393189 18.54654336 17.43915302
 22.23244266 23.84779346 22.56323875 18.31176816 27.39390314 13.27802243
 26.08865044 25.1781995  25.11313257 21.31957919 17.49737733 23.83688786
 22.81329826 26.9506226 ]
shape:(20,)

***出力1***
[1.]
shape:(1,)

出力合計: 1.0

##### 結果表示 #####
***中間層出力***
[1.71104546 4.92065362 7.75013795 1.75830799 4.55204153 7.02231455
 1.99393682 4.98794094 7.72271424 1.50531795]
shape:(10,)

***出力***
[1.]
shape:(1,)

***訓練データ***
[1]
shape:(1,)

***交差エントロピー誤差***
-9.999999505838704e-08
shape:()

